
service: cfn-transcoder-pipeline

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  variableSyntax: "\\${((?!AWS)[ ~:a-zA-Z0-9._'\",\\-\\/\\(\\)]+?)}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'logs:CreateLogGroup'
        - 'logs:CreateLogStream'
        - 'logs:PutLogEvents'
      Resource: 'arn:aws:logs:*:*:*'
    - Effect: Allow
      Action:
        - 'elastictranscoder:*'
        - 'iam:PassRole'
      Resource:
        - '*'

functions:
  pipeline:
    handler: functions/handler.pipelineHandler

resources:
  Outputs:
    PipelineArn:
      Description: A custom resource for creating Elastic Transcoder Pipelines
      Value:
        Fn::GetAtt: 
          - PipelineLambdaFunction
          - Arn
      Export:
        Name:
          Fn::Sub: "${AWS::StackName}-arn"

plugins:
  - serverless-webpack