
service: cfn-transcoder-pipeline

custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    packager: yarn
    excludeFiles: src/**/*.test.js
    includeModules:
      packagePath: "./package.json"
      forceExclude:
        - aws-sdk

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  variableSyntax: "\\${((?!AWS)[ ~:a-zA-Z0-9._'\",\\-\\/\\(\\)]+?)}"
  logRetentionInDays: 3
  deploymentBucket:
    name: ${cf:marketing-resources-prod.DeploymentBucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'logs:CreateLogGroup'
        - 'logs:CreateLogStream'
        - 'logs:PutLogEvents'
      Resource: 'arn:aws:logs:*:*:*'
    - Effect: Allow
      Action:
        - 'elastictranscoder:*'
        - 'iam:PassRole'
      Resource:
        - '*'

functions:
  pipeline:
    handler: functions/handler.pipelineHandler

resources:
  Outputs:
    PipelineArn:
      Description: A custom resource for creating Elastic Transcoder Pipelines
      Value:
        Fn::GetAtt: 
          - PipelineLambdaFunction
          - Arn
      Export:
        Name:
          Fn::Sub: "${AWS::StackName}-arn"

plugins:
  - serverless-webpack